apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      run: frontend
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/abzed/udagram-frontend:v2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
          limits:
            memory: 1536Mi
            cpu: 200m
